name: .NET build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies repository
      run: dotnet restore Clup-MemberShip/ClubMemberShip.Repo/ClubMemberShip.Repo.csproj

    - name: Build repository
      run: dotnet build --no-restore Clup-MemberShip/ClubMemberShip.Repo/ClubMemberShip.Repo.csproj

    - name: Restore dependencies service
      run: dotnet restore Clup-MemberShip/ClubMemberShip.Service/ClubMemberShip.Service.csproj

    - name: Build service
      run: dotnet build --no-restore Clup-MemberShip/ClubMemberShip.Service/ClubMemberShip.Service.csproj

    - name: Restore dependencies web razor page
      run: dotnet restore Clup-MemberShip/ClubMemberShip.Test/ClubMemberShip.Test.csproj

    - name: Build web razor page
      run: dotnet build --no-restore Clup-MemberShip/ClubMemberShip.Present/ClubMemberShip.Web.csproj
