name: .NET Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies web razor page
      run: dotnet restore Clup-MemberShip/ClubMemberShip.Test/ClubMemberShip.Test.csproj
      
    - name: Unit Test
      run: dotnet test --no-restore Clup-MemberShip/ClubMemberShip.Test/ClubMemberShip.Test.csproj
